# Change these first
owner: sant-sh
repo: status

sites:
  - name: Personal
    url: $PERSONAL
  - name: Yunohost
    url: $YUNOHOST
  - name: HomeLab
    url: $HOMELAB
  - name: Docker
    url: $DOCKER

status-website:
  cname: status.sant.sh
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server Health Status
  introTitle: "Personal monitoring served by **Santosh** "
  introMessage: Internal & External Site Monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
